<a href="https://colab.research.google.com/github/rollways/JDHW/blob/main/W1Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Z-SCORE

In [ ]:
import numpy as np
from scipy import stats

In [ ]:
data = np.array([200,300,400,600,1000])
data0 = [200,300,400,600,1000]
data

array([ 200,  300,  400,  600, 1000])

In [ ]:
data.shape

(5,)

In [ ]:
print(type(data))
print(type(data0))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
zscore = stats.zscore(data)
zscore.round(2)

array([-1.06, -0.71, -0.35,  0.35,  1.77])

### MIN-MAX

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data2 = np.array([[200],[300],[400],[600],[1000]])
minmax = scaler.fit_transform(data2)
minmax

array([[0.   ],
       [0.125],
       [0.25 ],
       [0.5  ],
       [1.   ]])

In [ ]:
print(data2)
print(data2.shape)

[[ 200]
 [ 300]
 [ 400]
 [ 600]
 [1000]]
(5, 1)
